ALTER TABLE "User" ADD COLUMN "theme" TEXT NOT NULL DEFAULT 'system';
ALTER TABLE "User" ADD COLUMN "applyThemeToAdmin" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "applyThemeToBooking" BOOLEAN NOT NULL DEFAULT false;
